/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TestSupabaseRouteImport } from './routes/test-supabase'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminManageActivitiesRouteImport } from './routes/admin/manage-activities'
import { Route as AdminManageMembersRouteImport } from './routes/admin/manage-members'
import { Route as AdminManageProjectsRouteImport } from './routes/admin/manage-projects'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStaticContentRouteImport } from './routes/admin/static-content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSupabaseRoute = TestSupabaseRouteImport.update({
  id: '/test-supabase',
  path: '/test-supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManageActivitiesRoute = AdminManageActivitiesRouteImport.update({
  id: '/manage-activities',
  path: '/manage-activities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManageMembersRoute = AdminManageMembersRouteImport.update({
  id: '/manage-members',
  path: '/manage-members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManageProjectsRoute = AdminManageProjectsRouteImport.update({
  id: '/manage-projects',
  path: '/manage-projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaticContentRoute = AdminStaticContentRouteImport.update({
  id: '/static-content',
  path: '/static-content',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/activities': typeof ActivitiesRoute
  '/articles': typeof ArticlesRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/projects': typeof ProjectsRoute
  '/signup': typeof SignupRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage-activities': typeof AdminManageActivitiesRoute
  '/admin/manage-members': typeof AdminManageMembersRoute
  '/admin/manage-projects': typeof AdminManageProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/static-content': typeof AdminStaticContentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/articles': typeof ArticlesRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/projects': typeof ProjectsRoute
  '/signup': typeof SignupRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage-activities': typeof AdminManageActivitiesRoute
  '/admin/manage-members': typeof AdminManageMembersRoute
  '/admin/manage-projects': typeof AdminManageProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/static-content': typeof AdminStaticContentRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/activities': typeof ActivitiesRoute
  '/articles': typeof ArticlesRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/projects': typeof ProjectsRoute
  '/signup': typeof SignupRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage-activities': typeof AdminManageActivitiesRoute
  '/admin/manage-members': typeof AdminManageMembersRoute
  '/admin/manage-projects': typeof AdminManageProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/static-content': typeof AdminStaticContentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/activities'
    | '/articles'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/members'
    | '/projects'
    | '/signup'
    | '/test-supabase'
    | '/admin/applications'
    | '/admin/dashboard'
    | '/admin/manage-activities'
    | '/admin/manage-members'
    | '/admin/manage-projects'
    | '/admin/settings'
    | '/admin/static-content'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/articles'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/members'
    | '/projects'
    | '/signup'
    | '/test-supabase'
    | '/admin/applications'
    | '/admin/dashboard'
    | '/admin/manage-activities'
    | '/admin/manage-members'
    | '/admin/manage-projects'
    | '/admin/settings'
    | '/admin/static-content'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/activities'
    | '/articles'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/members'
    | '/projects'
    | '/signup'
    | '/test-supabase'
    | '/admin/applications'
    | '/admin/dashboard'
    | '/admin/manage-activities'
    | '/admin/manage-members'
    | '/admin/manage-projects'
    | '/admin/settings'
    | '/admin/static-content'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ActivitiesRoute: typeof ActivitiesRoute
  ArticlesRoute: typeof ArticlesRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  ProjectsRoute: typeof ProjectsRoute
  SignupRoute: typeof SignupRoute
  TestSupabaseRoute: typeof TestSupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-supabase': {
      id: '/test-supabase'
      path: '/test-supabase'
      fullPath: '/test-supabase'
      preLoaderRoute: typeof TestSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manage-activities': {
      id: '/admin/manage-activities'
      path: '/manage-activities'
      fullPath: '/admin/manage-activities'
      preLoaderRoute: typeof AdminManageActivitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manage-members': {
      id: '/admin/manage-members'
      path: '/manage-members'
      fullPath: '/admin/manage-members'
      preLoaderRoute: typeof AdminManageMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manage-projects': {
      id: '/admin/manage-projects'
      path: '/manage-projects'
      fullPath: '/admin/manage-projects'
      preLoaderRoute: typeof AdminManageProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/static-content': {
      id: '/admin/static-content'
      path: '/static-content'
      fullPath: '/admin/static-content'
      preLoaderRoute: typeof AdminStaticContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminManageActivitiesRoute: typeof AdminManageActivitiesRoute
  AdminManageMembersRoute: typeof AdminManageMembersRoute
  AdminManageProjectsRoute: typeof AdminManageProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaticContentRoute: typeof AdminStaticContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminManageActivitiesRoute: AdminManageActivitiesRoute,
  AdminManageMembersRoute: AdminManageMembersRoute,
  AdminManageProjectsRoute: AdminManageProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaticContentRoute: AdminStaticContentRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ActivitiesRoute: ActivitiesRoute,
  ArticlesRoute: ArticlesRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  ProjectsRoute: ProjectsRoute,
  SignupRoute: SignupRoute,
  TestSupabaseRoute: TestSupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
